version: '3.8'

services:
  bank-api:
    image: ghcr.io/xcyrodilx/bank-api:latest
    container_name: bank-api
    ports:
      - "9090:8080"
    restart: always

  bank-web:
    image: ghcr.io/xcyrodilx/bank-web:latest
    container_name: bank-web
    # REMOVED the problematic 'environment:' block
    ports:
      - "3000:80"
    depends_on:
      - bank-api
    restart: always
    environment:
      # Tells the frontend to connect to the backend using the Docker service name and internal port.
      - API_URL= "http://localhost:9090/api/v1"
